version: 2.1
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.3.rc1
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests

  workflows:
    version: 2.1
    test-all:
      jobs:
        - test_regression_model