version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/solar_prod_suvilahti_ml_model/requirements.txt
            py.test -vv packages/regression_model/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests

  upload_pretrained_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            ./scripts/publish_model.sh ./solar_prod_suvilahti_ml_model/

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - upload_pretrained_regression_model
      - test_ml_api:
          requires:
            - upload_pretrained_regression_model
          filters:
            branches:
              only: master
      - upload_pretrained_regression_model:
          requires:
            filters:
              branches:
                only: master
